name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'jolt-minimal-glue-v5-4'
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@v4.0.2

      - name: Build Windows libraries
        shell: cmd
        run: scripts\build_windows.bat

      - name: Upload Windows libraries
        uses: actions/upload-artifact@v4
        with:
          name: libs_windows
          path: bin

  linux:
    name: Linux
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@v4.0.2

      - name: Install cross-compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Build Linux libraries
        run: bash scripts/build_linux.sh

      - name: Upload Linux libraries
        uses: actions/upload-artifact@v4
        with:
          name: libs_linux
          path: bin

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@v4.0.2

      - name: Build macOS libraries
        run: bash scripts/build_macos.sh

      - name: Upload macOS libraries
        uses: actions/upload-artifact@v4
        with:
          name: libs_osx
          path: bin

  combine:
    name: Combine artifacts
    runs-on: ubuntu-latest
    needs: [windows, linux, macos]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display artifact structure
        run: find artifacts -maxdepth 4 -type f | sort

      - name: Combine artifacts
        run: |
          mkdir jolt_libs
          cp -r artifacts/libs_windows/* jolt_libs/
          cp -r artifacts/libs_linux/* jolt_libs/
          cp -r artifacts/libs_osx/* jolt_libs/

      - name: Archive artifacts
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z jolt_libs.7z ./jolt_libs/

      - name: Upload combined artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: jolt_libs.7z

      - name: Delete intermediate artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            libs_windows
            libs_linux
            libs_osx
